### ISSUE TITLE
Category Filter Component

### ISSUE THREAD

**Issue by BerkayBideci** [202303-PRM-TR-FEW/capstone-template-team-3#20]
![3](https://github.com/hunctasci/capstone-template-team-3/assets/78705348/20613ba3-5bf3-42f1-b987-2b29290b33de)

Category Filter Component with five options should be implemented in the project. Each option should be clickable and filter projects accordingly.

**Comment by sesamemaki** [comment]
Category icons color should be recolored to match the one in the UI design (second pic).

![image](https://github.com/202303-PRM-TR-FEW/capstone-template-team-3/assets/99922048/fdb30348-3d30-4da9-ad33-d5fbfc86eee3)

![image](https://github.com/202303-PRM-TR-FEW/capstone-template-team-3/assets/99922048/dab4bd55-10fe-4676-a091-438ca4c5e2a1)
